# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03f983bac5e9db6b15a159579fd6ef58a7a59fe404e06309e395cfb61968ad3be55e081d1dcfefdf38fea4adbc1cde6a9779f56c42ee5d77b58eb166bed0f6af

test:
  secret_key_base: d91cd969bba87f6abf0bb9424a06126db5a65a51e8522f4e1632fa4decdfd51b45ffc1da32b6b4a76fe036a2340d52872f71b4c709666582b875c53c55a14d14

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
